spring:
  application:
    name: app

  profiles:
    active: dev

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://f5c0d176d7c67ea7a90e4903386d9cd3@o4511656490631168.ingest.de.sentry.io/4511656504328272
  send-default-pii: true