spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    output:
      ANSI:
        enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://87444bfc3622787d0bbc9fb2b89c6307@o4509350427295744.ingest.us.sentry.io/4509350461898752
  send-default-pii: true