setup:
	./gradlew wrapper --gradle-version 9.5.0

clean:
	./gradlew clean

build:
	./gradlew clean build

run:
	./gradlew bootRun

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

.PHONY: setup clean build run test report lint